language: node_js

stages:
  - test
  - release

node_js:
  - 15

before_script:
  - npm run build

jobs:
  include:
    - stage: release
      node_js: 15
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run semantic-release
        on:
          branch: main

env:
  global:
    secure: "Hrc+13GJeFhqXa6cusUWBAzDf3DPKoyWlwr7z6X9LK9UpaoZNh492xEbYsVi/hN6lOE0YEe80dTBPMAqlcpDNxJg3+JGmWhzIx+sstqMTs766XOhaK0somLPvpoFbzmShz9zLO4uIQ1o55iGOQdzdMbSk9w8lJInQRgLwdclBPRyhmbTNpeOwkwEIWkbC0vHKN4Go9k47dCyU4ZY1fZLr6b6VGvCoCJBp61DpIQr49nFa1xrvQ5LOpa2uH1U2LJy/jIF715ePXsk92sTCpp7xtODTi/Y5/Zo6TKvvoj8RSYJ2Yl1A1ChoblWancNx1T7bk9egNfcfGms92ImdK9r+PGUY98zhts9AHK5w8sKqjBWlTU+OZns52YFKrKSoIloirRtIoo9hRyXwuJGugQzYi8/p/9BB80d5K8FzWJxPL52MDiNd0pcOu60nP5X3fQ5bo+MfAV/bPKxNHigxtge9EbpjQumcAzRZuLIZFnUnfVv/UCowDfFLmtyyuS+gLBIXvcTqCOk9VuMfslOiWV331RBoC5CBkw9nn1sbs8IlWUiEm9Qk/UL97faPsuiNG2yDB6lA/UC7LOn2p6id40TiDhkn9/yJjcbXjQabAEXtn85lepOfUa32fQPAV5DQ66DRzQUTuMT6XKv0h2thwmf8MF5cO/QdTAW7/scLD96ys0="
