language: node_js

stages:
  - test
  - release

node_js:
  - 15

before_script:
  - npm run build

jobs:
  include:
    - stage: release
      node_js: 15
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
        on:
          branch: main
